# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];
  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.kernelParams = ["nouveau.config=NvClkMode=2"];
  boot.extraModulePackages = [];
  environment.sessionVariables = {
    WLR_NO_HARDWARE_CURSORS = "1";
    WLR_REDERER_ALLOW_SOFWWARE = "1";
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-partlabel/cryptroot";

  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 25; # lower if you've got lots of RAM
    priority = 100;
  };

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    options = ["subvol=@root" "compress=zstd" "noatime"];
    fsType = "btrfs";
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    options = ["subvol=@nix" "compress=zstd" "noatime"];
    fsType = "btrfs";
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/cryptroot";
    options = ["subvol=@persist" "compress=zstd" "noatime"];
    fsType = "btrfs";
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptroot";
    options = ["subvol=@log" "compress=zstd" "noatime"];
    fsType = "btrfs";
  };

  # Make critical paths persistent by bind-mounting them into /persist
  environment.etc."/nixos".source = "/persist/etc/nixos";
  environment.persistence."/persist" = {
    directories = [
      "/var/lib/bluetooth"
      "/var/lib/nixos"
      "/var/lib/systemd/coredump"
      "/var/lib/NetworkManager" # wifi credentials
      "/home"
    ];
    files = [
      "/etc/machine-id"
    ];
  };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = "x86_64-linux";
  # networking.interfaces.enp3s0f0.useDHCP = lib.mkDefault true;
}
